export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Finance 2.0',
  headLine: 'New era to the decentralized finance',
  description:
    'Get access to the most popular smart contract protocols from the top leading Defi platforms in one dashboard,  earn from multiple passive strategies like liquidity provider, staking, lending, borrowing...',
  buttonLabel: 'Learn More',
  imgStart: false,
  img: require('../../images/svg-1.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Defi Options',
  headLine: 'All services found in the Defi world',
  description:
    'Access to services from Decentralized platforms, Token prices, Comparison of the market and more...',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/svg-2.svg'),
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};
export const homeObjThree = {
  id: 'signup',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headLine: 'Unlimited transactions with zero fees',
  description:
    'Get acces to our exclusive app that allows you to send unlimited transactions without gettingcharged any fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-3.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};
