export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headLine: 'Unlimited transactions with zero fees',
  description:
    'Get acces to our exclusive app that allows you to send unlimited transactions without gettingcharged any fees.',
  buttonLabel: 'Learn More',
  imgStart: false,
  img: require('../../images/svg-1.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'Defi Options',
  headLine: 'Unlimited transactions with zero fees',
  description:
    'Get acces to our exclusive app that allows you to send unlimited transactions without gettingcharged any fees.',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/svg-2.svg'),
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};
export const homeObjThree = {
  id: 'Contact',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headLine: 'Unlimited transactions with zero fees',
  description:
    'Get acces to our exclusive app that allows you to send unlimited transactions without gettingcharged any fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-3.svg'),
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
};
